Add a sensible readme file
matrix-org/matrix-ansible-synapse pull request #7
Opened 2018-12-02 23:18 UTC by madonius

Fix #5 
Added a more sensible readme than ansible-galaxy's default

2018-12-02 23:23 UTC, jcgruenhage requested changes

2018-12-02 23:23 UTC, jcgruenhage commented on README.md
> +| matrix_synapse_skip_ssl | false
This table is broken.

2018-12-02 23:23 UTC, jcgruenhage commented on README.md
> +| matrix_synapse_version | "v0.28.1"
While that is the current version in the defaults, that should be fixed. There is no use in documenting broken state.

2019-02-17 23:37 UTC, madonius commented
See #11

2019-02-17 23:37 UTC, closed without merging